# Generated by Django 3.2.13 on 2023-12-03 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('data_de_compra', models.DateTimeField(auto_now_add=True, verbose_name='Data de compra')),
                ('feita_manutencao', models.BooleanField(default=False, verbose_name='Foi feita manutenção?')),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_de_compra'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_de_ingresso_no_campeonato', models.DateTimeField(auto_now_add=True, verbose_name='Data de ingresso no campeonato')),
                ('pais', models.CharField(max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=200, null=True)),
                ('diretor', models.CharField(blank=True, max_length=200, null=True)),
                ('funcionarios', models.CharField(blank=True, max_length=200, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_de_ingresso_no_campeonato'],
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_de_ingresso_na_equipe', models.DateTimeField(auto_now_add=True, verbose_name='Data de ingresso na equipe')),
                ('data_de_nascimento', models.DateTimeField(auto_now_add=True, verbose_name='Data Nascimento')),
                ('pais_de_origem', models.CharField(max_length=100)),
                ('cidade_natal', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaum.carro')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaum.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaum.equipe'),
        ),
    ]
