# Generated by Django 3.2.13 on 2023-12-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(default='XYZ-9876', max_length=10),
            preserve_default=False,
        ),
    ]
