# Generated by Django 3.2.13 on 2023-12-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaum', '0002_carro_placa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piloto',
            options={'ordering': ['-data_de_ingresso_na_equipe']},
        ),
    ]
