# Generated by Django 3.2.13 on 2023-12-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaum', '0003_alter_piloto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='data_de_nascimento',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Nascimento'),
        ),
    ]
