# Generated by Django 3.2.13 on 2023-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaum', '0004_alter_piloto_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='data_de_nascimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
    ]
